export const GET_ALBUMS_REQUEST = "GET_ALBUMS_REQUEST";
export const GET_ALBUMS_SUCCESS = "GET_ALBUMS_SUCCESS";
export const GET_ALBUMS_FAILURE = "GET_ALBUMS_FAILURE";

export const GET_ALBUMS_BY_SEARCH_REQUEST = "GET_ALBUMS_BY_SEARCH_REQUEST";
export const GET_ALBUMS_BY_SEARCH_SUCCESS = "GET_ALBUMS_BY_SEARCH_SUCCESS";
export const GET_ALBUMS_BY_SEARCH_FAILURE = "GET_ALBUMS_BY_SEARCH_FAILURE";
